CadastroDespesas/Models/Despesas/Despesas.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace CadastroDespesas.Models.Despesas
{
    public class Despesas
    {
        [Key]
        public int Id { get; set; }

        [MaxLength(100)]
        public string Descricao{ get; set; }

        public double Value { get; set; }

        public DateTime Date { get; set; }
    }
}

CadastroDespesas/Models/ErrorViewModel.cs
namespace CadastroDespesas.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

CadastroDespesas/Controllers/DespesasController.cs

using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using CadastroDespesas.Services;
using CadastroDespesas.Models;
using CadastroDespesas.DTOs;

namespace CadastroDespesas.Controllers
{
    public class DespesasController : Controller
    {
        private readonly ILogger<DespesasController> _logger;
        private readonly IDespesasService _despesasService;

        public DespesasController(ILogger<DespesasController> logger,
            IDespesasService despesasService)
        {
            _logger = logger;
            _despesasService = despesasService;
        }

        public async Task <IActionResult> Index()
        {
            var listDespesasDTO = new ListDespesasDTO();

            listDespesasDTO.Items = await _despesasService.FindBy(listDespesasDTO.StartDate, listDespesasDTO.EndDate);

            return View(listDespesasDTO);
        }

        [HttpPost]
        public async Task<IActionResult> Index(ListDespesasDTO listDespesasDTO)
        {
            try
            {
                listDespesasDTO.Items = await _despesasService.FindBy(listDespesasDTO.StartDate, listDespesasDTO.EndDate);

                return View(listDespesasDTO);
            }
            catch (Exception ex)
            {

                ModelState.AddModelError("CustomError", ex.Message);
                return View(listDespesasDTO);
            }

        }

        public async Task<IActionResult> Create()
        {
            var createDespesasDTO = new CreateDespesasDTO();

            return View(createDespesasDTO);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(CreateDespesasDTO createDespesasDTO)
        {
            try
            {
                await _despesasService.Create(createDespesasDTO);

                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {

                ModelState.AddModelError("CustomError", ex.Message);
                return View(createDespesasDTO);
            }
        }


        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

CadastroDespesas/Views/Despesas/Create.cshtml
@model CadastroDespesas.DTOs.CreateDespesasDTO

<form method="post">
    <div asp-validation-summary="All" class="text-danger"></div>
    <div class="row">
        <div class="col-md-12">
            <div class="form-group">
                <input asp-for="Descricao" placeholder="Digite a descrição" class="form-control" />
            </div>
        </div>
    </div>
    <br />
    <div class="row">
        <div class="col-md-12">
            <div class="form-group">
                <input asp-for="Date" type="date" placeholder="Digite a data" class="form-control" />
            </div>
        </div>
    </div>
    <br />
    <div class="row">
        <div class="col-md-12">
            <div class="form-group">
                <input asp-for="Value" type="number" placeholder="Digite a valor" class="form-control" />
            </div>
        </div>
    </div>
    <br />
    <div class="row">
        <div class="col-md-12">
            <div class="d-grid">
                <a asp-action="Index" class="btn btn-secondary btn-login text-uppercase fw-bold">Voltar</a>
            </div>
        </div>
    </div>
        <br />
    <div class="row">
        <div class="col-md-12">
            <div class="d-grid">
                <button type="submit" class="btn btn-primary btn-login text-uppercase fw-bold">Criar</button>
            </div>
        </div>
    </div>
</form>

CadastroDespesas/Views/Despesas/Index.cshtml
@model CadastroDespesas.DTOs.ListDespesasDTO

@{
    ViewData["Title"] = "Home Page";
}

<div class="row">
    <div class="col-sm">
        <h1>Lista de Despesas</h1>
    </div>
</div>

<div class="row">
    <div class="col-sm-12">
        <a asp-action="Create" asp-controller="Despesas" class="btn btn-primary btn lg btn-block">Nova Despesa</a>
    </div>
</div>

<form method="post">
    <div asp-validation-summary="All" class="text-danger"></div>
    <div class="row">
        <div class="col-md-4">
            <div class="form-group">
                <input asp-for="StartDate" type="date" placeholder="Digite a data inicial" class="form-control" />
            </div>
        </div>
        <div class="col-md-4">
            <div class="form-group">
                <input asp-for="EndDate" type="date" placeholder="Digite a data final" class="form-control" />
            </div>
        </div>
        <div class="col-md-4">
            <div class="form-group">
                <button type="submit" class="btn btn-primary btn-lg">Buscar</button>
            </div>
        </div>
    </div>
</form>

<div class="row">
    <div class="col-md">
        <table class="table">
            <thead>
                <tr>
                    <th>ID</th>
                    <th>Descrição</th>
                    <th>Data</th>
                    <th>Valor</th>
                </tr>
            </thead>
            <tbody>
                @if(Model.Items.Count > 0)
                {
                    foreach(var item in Model.Items)
                    {
                        <tr>
                            <td>@item.Id</td>
                            <td>@item.Descricao</td>
                            <td>@item.Date.ToString("dd/MM/yyyy")</td>
                            <td>@item.Value</td>
                        </tr>
                    }
                }
                else
                {
                    <tr><td colspan="4">Nenhum registro encontrado.</td></tr>
                }
            </tbody>
        </table>
    </div>
</div>

CadastroDespesas/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Cadastro Despesas</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/CadastroDespesas.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Despesas" asp-action="Index">Cadastro Despesas</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Despesas" asp-action="Index">Home</a>
                        </li>
   
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - CadastroDespesas <a asp-area="" asp-controller="Home" asp-action="Privacy"></a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.19.3/jquery.validate.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validation-unobtrusive/3.2.12/jquery.validate.unobtrusive.min.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>